In [1]:
pwd

'C:\\Users\\hk2\\Python_Session\\Session1'

In [3]:
import numpy as np
data = np.loadtxt('../dataset/test_data.txt',
                  skiprows=1,
                  delimiter=',')
print(data)

[[1.11e+02 1.00e+02 1.00e+06]
 [1.12e+02 2.00e+02 1.30e+06]
 [1.13e+02 1.20e+02 1.50e+06]]
